[lib]
name = "rust_miniscript_lib"
crate-type = ["staticlib"]

[package]
name = "rust_miniscript_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
miniscript = { version = "12.2.0", features = ["std", "compiler"] }
